spring:
 application:
  name: spring_basic
 datasource:
  url: jdbc:mysql://localhost:3306/spring_basic
  username: root
  password: "13022001"
  driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
    format_sql: true
    use_sql_comments: true
    generate_statistics: true
    highlight_sql: true
    show_sql: true
 mail:
  host: smtp.gmail.com
  port: 587
  username: [EMAIL_ADDRESS]
  password: [PASSWORD]
  default-encoding: UTF-8
  properties:
   mail.smtp.auth: true
   mail.smtp.starttls.enable: true
   mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory